"""Telegram Agent Usage Examples.

This file shows practical examples of using the Telegram agent for various automation tasks.
"""

import os
import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from src.agent import telegram_agent
from dotenv import load_dotenv

load_dotenv()


def example_send_blog_notification(chat_id: str, blog_title: str, blog_url: str):
    """Example: Send notification when new blog is published."""
    message = f"""
📝 *New Blog Post Published!*

{blog_title}

🔗 Read more: {blog_url}

_Posted by FDWA AI Automation Agency_
"""
    
    result = telegram_agent.send_message(
        chat_id=chat_id,
        text=message,
        parse_mode="Markdown",
        disable_web_page_preview=False
    )
    
    return result


def example_send_instagram_analytics(chat_id: str, likes: int, comments: int, reach: int):
    """Example: Send Instagram post analytics summary."""
    message = f"""
📊 *Instagram Post Performance*

👍 Likes: {likes}
💬 Comments: {comments}
👁 Reach: {reach}

Great engagement today! 🎉
"""
    
    result = telegram_agent.send_message(
        chat_id=chat_id,
        text=message,
        parse_mode="Markdown"
    )
    
    return result


def example_send_daily_summary(chat_id: str, posts_created: int, emails_sent: int, engagement_rate: float):
    """Example: Send daily automation summary."""
    message = f"""
🤖 *Daily AI Agent Summary*

✅ Tasks Completed:
• Blog posts created: {posts_created}
• Emails sent: {emails_sent}
• Engagement rate: {engagement_rate:.1f}%

📅 Date: {__import__('datetime').datetime.now().strftime('%Y-%m-%d')}

Keep up the great work! 💪
"""
    
    result = telegram_agent.send_message(
        chat_id=chat_id,
        text=message,
        parse_mode="Markdown"
    )
    
    return result


def example_send_error_alert(chat_id: str, error_type: str, error_message: str):
    """Example: Send error/alert notification."""
    message = f"""
⚠️ *Agent Alert*

🚨 Error Type: {error_type}
📝 Details: {error_message}

Please check the logs for more information.

_Timestamp: {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M:%S')}_
"""
    
    result = telegram_agent.send_message(
        chat_id=chat_id,
        text=message,
        parse_mode="Markdown"
    )
    
    return result


def example_send_with_action_buttons(chat_id: str):
    """Example: Send message with inline keyboard buttons."""
    reply_markup = '''{
        "inline_keyboard": [
            [
                {"text": "✅ Approve", "callback_data": "approve"},
                {"text": "❌ Reject", "callback_data": "reject"}
            ],
            [
                {"text": "✏️ Edit", "callback_data": "edit"},
                {"text": "👁 Preview", "callback_data": "preview"}
            ]
        ]
    }'''
    
    message = """
📝 *New Blog Draft Ready*

Title: "10 AI Automation Tips for 2024"
Length: 1,200 words

Would you like to approve this post?
"""
    
    result = telegram_agent.send_message(
        chat_id=chat_id,
        text=message,
        parse_mode="Markdown",
        reply_markup=reply_markup
    )
    
    return result


def example_send_scheduled_post_image(chat_id: str, image_path: str, caption: str):
    """Example: Send generated image with caption for review."""
    # For local files, you need to upload them
    # For URLs, just pass the URL
    
    result = telegram_agent.send_photo(
        chat_id=chat_id,
        photo=image_path,  # Can be file_id, URL, or file path
        caption=f"📸 {caption}\n\n_Generated by AI Image Agent_",
        parse_mode="Markdown"
    )
    
    return result


def example_check_for_commands():
    """Example: Check for new commands/messages from Telegram."""
    result = telegram_agent.get_updates(limit=100, timeout=10)
    
    if result["success"]:
        updates = result["data"].get("result", [])
        
        for update in updates:
            if "message" in update:
                msg = update["message"]
                text = msg.get("text", "")
                chat_id = msg["chat"]["id"]
                
                # Handle commands
                if text.startswith("/start"):
                    telegram_agent.send_message(
                        chat_id=str(chat_id),
                        text="👋 Welcome to FDWA AI Agent! I can help you with automated content creation."
                    )
                
                elif text.startswith("/status"):
                    telegram_agent.send_message(
                        chat_id=str(chat_id),
                        text="✅ All systems operational!"
                    )
                
                elif text.startswith("/help"):
                    help_text = """
*Available Commands:*
/start - Start the bot
/status - Check agent status
/help - Show this help message
/blog - Generate new blog post
/instagram - Post to Instagram
"""
                    telegram_agent.send_message(
                        chat_id=str(chat_id),
                        text=help_text,
                        parse_mode="Markdown"
                    )
    
    return result


def example_broadcast_to_multiple_chats(chat_ids: list, message: str):
    """Example: Broadcast a message to multiple chats/channels."""
    results = []
    
    for chat_id in chat_ids:
        result = telegram_agent.send_message(
            chat_id=chat_id,
            text=message,
            parse_mode="Markdown"
        )
        results.append({
            "chat_id": chat_id,
            "success": result["success"]
        })
    
    return results


def example_answer_callback_query(callback_query_id: str, action: str):
    """Example: Respond to inline button press."""
    if action == "approve":
        text = "✅ Post approved! Publishing now..."
        show_alert = True
    elif action == "reject":
        text = "❌ Post rejected."
        show_alert = True
    else:
        text = "Processing..."
        show_alert = False
    
    result = telegram_agent.answer_callback_query(
        callback_query_id=callback_query_id,
        text=text,
        show_alert=show_alert
    )
    
    return result


# Integration with existing agents
def integrate_with_blog_agent(chat_id: str):
    """Example: Integration with blog_email_agent.py"""
    from src.agent.blog_email_agent import generate_blog_content
    
    # Send notification that blog generation is starting
    telegram_agent.send_message(
        chat_id=chat_id,
        text="🤖 Starting blog generation..."
    )
    
    try:
        # Generate blog (this is the actual agent call)
        blog_content = generate_blog_content()
        
        # Send success notification
        telegram_agent.send_message(
            chat_id=chat_id,
            text=f"✅ Blog generated successfully!\n\nPreview: {blog_content[:200]}..."
        )
    
    except Exception as e:
        # Send error notification
        example_send_error_alert(chat_id, "Blog Generation", str(e))


def main():
    """Run example usage scenarios."""
    print("Telegram Agent Usage Examples")
    print("=" * 60)
    
    # Get chat ID
    chat_id = os.getenv("TELEGRAM_TEST_CHAT_ID")
    if not chat_id:
        chat_id = input("Enter your Telegram chat ID: ")
    
    if not chat_id:
        print("No chat ID provided.")
        return
    
    # Show menu
    print("\nAvailable Examples:")
    print("1. Send blog notification")
    print("2. Send Instagram analytics")
    print("3. Send daily summary")
    print("4. Send error alert")
    print("5. Send message with action buttons")
    print("6. Check for commands")
    print("7. Test blog integration")
    print("0. Exit")
    
    choice = input("\nSelect example (0-7): ")
    
    if choice == "1":
        result = example_send_blog_notification(
            chat_id,
            "How AI is Transforming Business Automation",
            "https://fdwa.com/blog/ai-automation"
        )
        print(f"Result: {result}")
    
    elif choice == "2":
        result = example_send_instagram_analytics(chat_id, 342, 28, 1540)
        print(f"Result: {result}")
    
    elif choice == "3":
        result = example_send_daily_summary(chat_id, 3, 15, 8.5)
        print(f"Result: {result}")
    
    elif choice == "4":
        result = example_send_error_alert(chat_id, "API Connection", "Failed to connect to Instagram API")
        print(f"Result: {result}")
    
    elif choice == "5":
        result = example_send_with_action_buttons(chat_id)
        print(f"Result: {result}")
    
    elif choice == "6":
        result = example_check_for_commands()
        print(f"Found {len(result.get('data', {}).get('result', []))} updates")
    
    elif choice == "7":
        integrate_with_blog_agent(chat_id)
    
    print("\n✅ Example completed!")


if __name__ == "__main__":
    main()
